# Generated by Django 5.2.8 on 2026-01-30 09:47

import django.db.models.deletion
import mainsite.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=254)),
                ('format', models.IntegerField(choices=[(0, 'Portrait'), (1, 'Landscape')], default=0)),
                ('alignment', models.IntegerField(choices=[(0, 'Left'), (1, 'Center')], default=0)),
                ('posX', models.PositiveSmallIntegerField(default=80)),
                ('posY', models.PositiveSmallIntegerField(default=98)),
                ('scale', models.PositiveSmallIntegerField(default=90)),
                ('image', models.FileField(blank=True, upload_to='uploads/pdftemplates')),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdftemplates', to='issuer.issuer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(mainsite.mixins.ResizeUploadedImage, mainsite.mixins.ScrubUploadedSvgImage, mainsite.mixins.PngImagePreview, models.Model),
        ),
        migrations.CreateModel(
            name='PDFEditorQrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdfeditorqrcode', to='issuer.qrcode')),
                ('pdftemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfeditor.pdftemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PDFEditorLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningpath', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdfeditorlearningpath', to='issuer.learningpath')),
                ('pdftemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfeditor.pdftemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PDFEditorBadgeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeinstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdfeditorbadgeinstance', to='issuer.badgeinstance')),
                ('pdftemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfeditor.pdftemplate')),
            ],
        ),
    ]
