# Generated by Django 5.2.8 on 2026-03-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0027_alter_altchachallenge_id_alter_iframeurl_id'),
        ('pdfeditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFEditorIframeUrl',
            fields=[
                ('iframeurl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainsite.iframeurl')),
            ],
            bases=('mainsite.iframeurl',),
        ),
    ]
